<?php
return array(
    // Those names are shared for all models
    // To make it specific, prefix it with table name
	'permission' => '権限',
	'no' => 'No',
	'is_public_flag' => '公開状態',
	'contact' => '連絡先',
	'agent_id' => '代理店',
	'channel_id' => 'チャンネル',
	'display_position' => '表示枠',
	'start_point' => 'スタートポイント',
	'display_width' => '左',
	'display_height' => '上',
	'remarks' => '備考',
	'led_eq_max_number' => 'LED機器最大数',
	'external_width' => '外部接点幅',
	'start_x' => '左',
	'start_y' => '上',
	'client_id' => 'クライアント',
	'total_client'=>'クライアント数',
	'total_led' =>'LED数',
    'id' => '会員No',
    'created_at' => '登録日時',
    'updated_at' => '更新日時',
    'date_modified' => '代理店更新日時',
    'deleted_at' => '削除日時',
    'name' => '名',
    'price' => '参加費',
    'price_detail' => '参加費補足説明',
    'lecturer' => '講師プロフィール',
    'purpose' => '目的・狙い',
    'audiences' => '受講対象者',
    'goal' => '到達目標',
    'choice_theme' => 'テーマ',
    'choice_length' => '期間',
    'theme' => 'テーマ',
    'fullname' => 'ユーザ名',
    'username' => 'ログインID',
    'email' => 'メールアドレス',
    'email_confirmation' => 'メールアドレス（確認）',
    'password' => 'パスワード',
    'admin_password' => '管理者パスワート',
    'current_password' => '現在のパスワード',
    'new_password' => '新しいパスワード ',
    'new_password_confirmation' => '新しいパスワード（確認)',
    'password_confirmation' => 'パスワード（再入力）',
    'seen_at' => '最終ログイン日時',

    'seminar_id' => 'セミナーID',
    'is_repr_join' => '代表者の方はセミナーに参加しますか？',
    'title' => 'タイトル',
    'content' => '内容',

    'person_id' => '代表者 ID',
    'company' => '勤務先名称',
    'phone' => '連絡先電話番号',
    'phone1' => '連絡先電話番号(左)',
    'phone2' => '連絡先電話番号(中央)',
    'phone3' => '連絡先電話番号(右)',
    'fixed_phone' => '連絡先電話番号',
    'mobile_phone' => '携帯電話番号',
    'mobile' => '携帯電話番号',
    'mobile1' => '携帯電話番号',
    'mobile2' => '携帯電話番号',
    'mobile3' => '携帯電話番号',
    'is_send_home' => '参加証等送付先',
    'postal' => '送付先郵便番号',
    'zip1' => '郵便番号(左)',
    'zip2' => '郵便番号(右)',
    'send_address' => '送付先ご住所',
    'choice_pref' => '都道府県',
    'ward' => '市区町村',
    'area' => '番地',
    'building' => '病棟・号数',
    'refer_source' => '知ったきっかけ',
    'is_subscribed' => 'DMを送ってもよいか',
    
    'application_id' => '申込書ID',
    
    'last_name' => '氏名(氏)',
    'first_name' => '氏名(名)',
    'experience' => '職務経験年数',
    
    'report' => '詳細レポート',
    'voices' => '受講者の声',
    
    'ab_seminar_id' => '抽象セミナーID',
    'open_at' => '開催日',
    'venue' => '開催地',
    'venues' => '開催地',
    'choice_venue' => '開催地',
    'venue_name' =>'会場名',
    'venue_url' =>'会場URL',
    'address' => '住所',
    'tel' => '電話番号',
    'access_guide' => '会場',
    'capacity_display' => '定員（表示）',
    'capacity_real' => '定員（webフォーム）',
    'year' => '年度',
    'venue_address' => '所在地',
    'zipcode' => '郵便番号',
    
    'url' => '遷移先URL',
    
    'is_new_window' => '新規ウィンドウ',
    'written_at' => '日付',
    'updated_by' => '最終更新者／登録者',
    'modified_by' => '最終更新者',
    
    'affiliation' => '所属・肩書',
    'profile' => 'プロフィール',
    
    
    'book_title' => '書籍名',
    'choice_status' => '状態',
    'heading' => '見出し',
    'body' => '本文',
    'choice_position' => '画像位置',
    
    'from_at' => '日付',
    'until_at' => '日付',
    'member_id' => '会員No',
    
    'seminar_detail' => '詳細情報',
    'programs' => 'プログラム',
    'books' => '書籍',
    'lecturers' => '講師',

    'headline_id' => 'ニュースID',
    'admin_id' => 'アカウントID',
    
    'upload' => '画像',
    'paragraph' => '',
    
    'from_time' => '開始時間',
    'to_time' => '終了時間',
    'detail'  => '内容',
    'is_rest' => '休憩',
    'choice_attend_date' => 'セミナー参加日程',
    
    'venue_summary' => '<div class="row"><div class="col-md-4">開催日</div><div class="col-md-4">開催地</div><div class="col-md-4">定員</div></div>',
    'seminar_status' => '状態<br>セミナー',
    'report_status' => '状態<br/>レポート',

    'day_1' => '1日目のキャンセル数',
    'day_2' => '2日目のキャンセル数',

   
    'agent' =>'代理店',
	'client' => 'クライアント',
	'client_public_flag' => 'クライアント公開状態',
	'agent_public_flag' => '代理店公開状態',
	'channel_public_flag' => 'チャンネル公開状態',
    'use_news_flag' => 'ニュース利用',
	'use_external_flag' => '外部接点',
	//チャンネル
    'client_name' =>'クライアント名',
    'agent_name' =>'代理店名',
	'channel_name' => 'チャンネル名',
	'lot_no' => 'ロットNo',
	'use_push_flag' => 'プッシュ機能',
	'emergency_flag' => '緊急通知',
    'required' => [
        'email_confirmation',
        'password_confirmation',
    ],

    'led_name' => 'LED名',
    'remarks' => '備考',
    'serial_no' => 'シリアルNo',
    'installation_destination' => '設置場所',
    'connection_status' => '接続状態',
	'installation_date_detail' => '稼働開始日',
    'ip' => '接続元IP',
    'installation_date' => '設置日',
	'emergency_flag1' => '緊急',
	'emergency_flag2' => '通知',
	'use_push_flag1' => 'プッシュ',
    'use_push_flag2' => '機能',
	'channel_public_flag1' => 'チャンネル',
    'channel_public_flag2' => '公開状態',

    'reserved_delivery' => '配信予約',
    'reserved_date' => '予約日時',
    
);