<?php
return array(
	'is_public_flag' => '公開状態',
	'account_admin' => '管理者',
	'account_agent' => '代理店',
	'account_client' => 'クライアント',
	'client_title' => 'クライアント',
	'agent_title' => '代理店',
	'channel_title' => 'チャンネル',
	'account_title' => 'アカウント',
	'led_title' => 'LED',
	'create_channel' =>'Create Channel',
	'channel_list' => 'Channel Lists',
    'create'           => '登録',
    'update'           => '更新',
    'edit'         	   => '更新',
    'top'              => 'TOPページ',
	'agent'            => '代理店管理',
	'agents'           => '代理店一覧',
	'agents/create'    => '代理店登録',
	'client'            => 'クライアント管理',
	'clients'           => 'クライアント一覧',
	'clients/create'    => 'クライアント登録',
	'channel'            => 'チャンネル管理',
	'channels'           => 'チャンネル一覧',
	'channels/create'    => 'チャンネル登録',
	'account'            => 'アカウント管理',
	'accounts'           => 'アカウント一覧',
	'accounts/create'    => 'アカウント登録',
	'client_detail_btn' => 'クライアント詳細',
	'agent_detail_btn' => '代理店詳細',
	'channel_detail_btn' => 'チャンネル詳細',
	'led_detail_btn' => 'LED詳細',
	'emergencys' => '緊急通知一覧',

	'tool'             => '管理ツール',
	'encrypt'            => '復号ツール',
	'led'             => 'LED管理',
	'leds'            => 'LED一覧',
	'change'          => '変更',
	'channel_operation'          => 'チャンネル操作',
	'client_operation'          => 'クライアント操作',
	'led_operation'          => 'LED操作',
	'agent_operation'          => '代理店操作',
	'change_password' => 'パスワード変更',
	'reset_password' => 'パスワードリセット',
    'admin_password' => '管理者パスワート',

	//button label
    'search_clear_btn' => '検索条件をクリア',
    'search_btn' => '検索',
    'top_page_btn' => 'TOPページへ',
    'add_btn' => '追加',
    'list_btn' => '一覧',
    'create_btn' => '登録',
	'delete_btn' => '削除',
	'edit_btn' => '編集',
	'update_btn' => '更新',
	'cancel_btn' => 'キャンセル',
    'back_btn' => '戻る',
	'copy_btn' => 'コピー',
	'create_new_btn' => '新規作成',

   //channel button label
    'preview_btn' => 'プレビュー',
	'setting_download_btn' => '設定ダウンロード',
	'update_channel_btn' => 'アップデート',
	'delivery_reserve_btn' => '配信予約',
	'emergency_notice_btn' => '緊急通知',
	'outside_contact_btn' => '外部接点',
	'sort_btn' => '並べ替え',
	'notice_btn' => '通知',
	'setting_btn' => '設定',
	'reserve_btn' => '予約',

    'application/'=> '申込',
    'headline/'   => 'ニュース',
    'admin/'      => 'アカウント',

    'member'      => '会員',
    'basic'       => 'セミナー基本情報',
    'seminar'     => 'セミナー',
    'application' => '申込',
    'headline'    => 'ニュース',
    'admin'       => 'アカウント',
    'withdraw'    => 'キャンセル',
    'withdraw_button' => '入力',

    'hearts' => [
        'venue'    => '開催地情報',
        'lecturer' => '講師情報',
        'book'     => '書籍情報',
        'program'  => 'プログラム',
        'program/1'  => 'プログラム',
        'program/2'  => 'プログラム',
        'paragraph' => 'レポート詳細',
    ],

    'detail'      => '詳細',
    'confirm'     => '確認',
    'login'       => 'SEKISHIN',
	'login_subtitle' => 'LEDコントローラー',
	'login_form_top' =>'管理画面',
    'delete_question' => 'を削除しますか?',
    'delete_done' => 'を削除しました。',
    'delete'      => '削除',
    'back_list'   => '一覧画面へ',
    'back_detail' => '詳細画面へ',
    'back_create' => '続けて登録する',
    'edit'        => '編集',
    'add'         => '追加',
    'cancel'      => 'キャンセル',

    'basic_detail'=> '基本',

    'relative'    => [
        'before'  => '前',
        'y'       => '年',
        'm'       => '月',
        'd'       => '日',
        'h'       => '時',
        'i'       => '分',
        's'       => '秒',
        'now'     => '今',
    ],
    'venue'       => '会場',
    'venues'      => [
        'create'  => '会場入力欄追加',
    ],
    'submodel_summary' => [
        'lecturers'    => '概要',
        'books'        => '概要',
        'programs'     => '概要',
    ],
    'report'        => 'レポート',
    'report_edit'   => 'レポート修正',
    'report_create' => 'レポート登録',
    'missing'       => '-',
    'paragraph'     => 'レポート',
    'program'       => 'プログラム',
    'program_day'   => ':day日目',
    'book'          => '書籍',
    'image'         => '画像',
    'lecturer'      => '講師',
    'lookup_zipcode'=> '検索',

    'detail_create'   => '詳細情報登録',
    'detail_edit'     => '詳細情報編集',

    'venue_filled' => '詳細情報確認',
    'venue_blank' => '詳細情報未登録',
    'map'         => '地図',

    'modify_account' => '変更アカウント',
    'login_id' => 'ログインID',
    'permission' => '権限',

    'not_existed' => '未登録',
    'overflow' => ':dayには申込み数よりも大きな値を設定出来ません。',

	//フラグ
	'in_activate'=> '無効',
	'activate'=> '有効',
	'public'=> '公開',
	'not_public'=> '非公開',
	'not_setting_emergency' => '未設定',
	'setting_emergency' => '通知中',
	'yes'=> 'あり',
	'no'=> 'なし',
	'top_title' => 'LEDing Board System トップ',
	'product_name'	=> 'LEDing Board System',

    'not_connected' => '未接続',
    'connected' => '接続中',
    'disconnected' => '切断中',

    'reserved_delivery' => '配信予約',
    'notifier' => '通知者',
    'notification' => '通知内容',
    'time_notification' => '通知日時',
    'new_emergency' => '新規作成',
);
